= Clerk
Aurora Openshift Paas <utvpaas@skatteetaten.no>
{version}
:doctype: book
:icons: font
:toc: left
:toclevels: 3
:sectlinks:

[introduction]
== Introduction

This documents describes the api of Clerk, an proxy to get information from the Kubernetes/OpenShift cluster.

Operations supported for now :
 - fetch a list of pods in your own namespace, optionally filtered on name of the application

[resources]

== How to use Clerk in your application
Clerk required a Authorization Bearer token that is the serviceAccount token your application is running in.

In order to get this token in a running application in your cluster you can read the file
``/var/run/secrets/kubernetes.io/serviceaccount/token``


== How to test an application against Clerk locally
Clerk requires an serviceaccount token that is in the same namespace as the pods you want to fetch. In order to obtain this
token you can run the following chain of commands

``oc get sa default -n $namespace -o json | jq -r ".secrets[0].name" | xargs -i oc get secret {} -o json | jq --arg name "token" '.data[$name]' -r | base64 -d > /tmp/clerk-token``

Where $namespace is the name of the namespace you want to fetch pods in.

Then read ``/tmp/clerk-token`` in your local profile

== Resources


[[overview]]
== Terms

[[overview-http-verbs]]
=== HTTP verbs
The API tries to follow standard HTTP and ReST conventions in how it uses HTTP verbs.
|===
| Verb | Usage

| `GET`
| Used for fetching resources. Idempotent.

| `POST`
| Used for creating new resources.

| `PUT`
| Used for updating existing resources. Only full updates (no patches). Idempotent.

| `DELETE`
| Used for deleting existing resources. Idempotent.
|===

[[overview-http-status-codes]]
=== HTTP status codes
The API tries to follow standard HTTP and ReST conventions in how it uses HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests. The response payload will vary depending on the endpoint used.

| `204 No Content`
| The request was successfully processed but did not return any response.

| `400 Bad Request`
| The request cannot be processed because for client side error (illegal argument or request).

| `404 Not Found`
| The requested resource count not be found.
|===



:leveloffset: +2
